-- Create 'tests' table
create table public.tests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  turnaround text,
  features text[],
  popular boolean default false
);

-- Create 'bookings' table
create table public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  patient_name text not null,
  phone text not null,
  address text not null,
  booking_date text,
  test_id bigint,
  test_name text,
  price numeric
);

-- Enable Row Level Security (RLS)
alter table public.tests enable row level security;
alter table public.bookings enable row level security;

-- Create Policies to allow public access (since we are using Anon key without auth for now)
-- Allow anyone to READ tests
create policy "Allow public read access"
  on public.tests for select
  using (true);

-- Allow anyone to INSERT bookings
create policy "Allow public insert access"
  on public.bookings for insert
  with check (true);

-- Seed Data (Initial Tests matching the design)
insert into public.tests (name, description, price, turnaround, features, popular)
values
  (
    'Redcliffe Vital Screening Package',
    'Screening of essential body parameters including Liver, Kidney, and Thyroid.',
    399,
    '12 hours',
    ARRAY['80+ Parameters', 'Thyroid Profile', 'Liver Function Test', 'Kidney Function Test'],
    true
  ),
  (
    'Full Body Checkup with Vitamin D & B12',
    'Complete health checkup covering all vital organs and vitamin deficiencies.',
    799,
    '24 hours',
    ARRAY['90+ Parameters', 'Vitamin D & B12', 'Iron Profile', 'HbA1c'],
    true
  ),
  (
    'Thyroid Profile Total',
    'Check your T3, T4, and TSH levels accurately.',
    199,
    '6 hours',
    ARRAY['T3, T4, TSH', 'Free Consultation'],
    false
  ),
  (
    'Diabetes Profile Comprehensive',
    'Advanced screening for diabetic patients including HbA1c and Average Blood Glucose.',
    499,
    '10 hours',
    ARRAY['HbA1c', 'Fasting Blood Sugar', 'Average Blood Glucose', 'Urine Routine'],
    false
  ),
  (
    'Senior Citizen Advance Package',
    'Tailored health checkup for senior citizens focusing on bone health and vital organs.',
    1299,
    '24 hours',
    ARRAY['Bone Health', 'Cardiac Risk Markers', 'Vitamin Profile', 'Complete Hemogram'],
    false
  );
