-- Create 'patients' table
create table public.patients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  phone text not null,
  age integer,
  gender text,
  email text,
  address text,
  blood_group text,
  medical_history text
);

-- Enable Row Level Security (RLS)
alter table public.patients enable row level security;

-- Create Policies to allow public access (adjust as needed for auth)
-- Allow public insert
create policy "Allow public insert access"
  on public.patients for insert
  with check (true);

-- Allow public read (optional, limit this in production)
create policy "Allow public read access"
  on public.patients for select
  using (true);

-- Allow public update based on phone number (simple logic for now)
create policy "Allow update via phone"
  on public.patients for update
  using (true)
  with check (true);
