-- 1. Update 'bookings' table to support Auth and Status
-- Using 'if not exists' logic where possible or simple checks
alter table public.bookings add column if not exists user_id uuid references auth.users(id);
alter table public.bookings add column if not exists status text default 'Booked'; -- 'Booked', 'Sample Collected', 'Report Ready'

-- 2. Create 'reports' table for PDF links
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  booking_id bigint references public.bookings(id),
  user_id uuid references auth.users(id),
  report_url text, -- Could be a public URL or storage path
  generated_at timestamp with time zone default now()
);

-- 3. Security Updates (Row Level Security)

-- Enable RLS on new tables
alter table public.reports enable row level security;

-- Update Bookings Policy: Users can only see their OWN bookings
-- First, drop insecure "public read" if it exists (optional, or we just add a restrictive one)
drop policy if exists "Allow public read access" on public.bookings;
drop policy if exists "Allow public insert access" on public.bookings;

-- New Policy: Users can select their own bookings
create policy "Users can view own bookings"
  on public.bookings for select
  using (auth.uid() = user_id OR phone = current_setting('request.jwt.claim.phone', true));

-- New Policy: Users can insert their own bookings
create policy "Users can insert own bookings"
  on public.bookings for insert
  with check (auth.uid() = user_id OR user_id is null); 

-- Reports Policy: Users can view their own reports
create policy "Users can view own reports"
  on public.reports for select
  using (auth.uid() = user_id);

-- 4. Create 'profiles' table (standard Supabase pattern for user data)
-- This handles the "Users table" requirement properly linked to Auth
create table if not exists public.profiles (
  id uuid references auth.users(id) primary key,
  full_name text,
  phone text,
  address text,
  updated_at timestamp with time zone
);

alter table public.profiles enable row level security;

create policy "Users can view own profile" 
  on public.profiles for select 
  using (auth.uid() = id);

create policy "Users can update own profile" 
  on public.profiles for update 
  using (auth.uid() = id);

-- Trigger to create profile on signup (optional but good practice)
-- (Skipping complex triggers for now to keep it simple, app can insert profile)
