// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wblzjieoofoqwhowfggp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndibHpqaWVvb2ZvcXdob3dmZ2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MDg2NjMsImV4cCI6MjA4NTQ4NDY2M30.y5JDFHyeE6QZ42dQbfwoZoVgvFsZ9ldlwN4sQj8WqT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});